/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Cropper: typeof import('./components/Cropper.vue')['default']
    ResponsiveTable: typeof import('./components/ResponsiveTable.vue')['default']
    ResponsiveTableColumn: typeof import('./components/ResponsiveTableColumn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
