services:
  server:
    image: eeg1412/wikimoe-guild-server:latest
    container_name: wikimoe-guild-server
    restart: unless-stopped
    ports:
      - '3120:3120'
    environment:
      - PORT=3120
      - MONGODB_URI=mongodb://mongo:27017/wikimoe-guild
      - LOG_LEVEL=info
      - TZ=Asia/Shanghai
    volumes:
      - ./server/keys:/app/server/keys
      - ./server/logs:/app/server/logs
      - ./server/public:/app/server/public
      - ./server/lock:/app/server/lock
      - ./server/utils/ip2location:/app/server/utils/ip2location
    networks:
      - wikimoe-guild
    depends_on:
      - mongo

  mongo:
    image: mongo:8.2.3-noble
    container_name: wikimoe-guild-mongo
    restart: unless-stopped
    volumes:
      - ./mongo_data:/data/db
    networks:
      - wikimoe-guild

networks:
  wikimoe-guild:
    driver: bridge

volumes:
  mongo_data:
